name: Auto Merge Update Branch

on:
  push:
    branches:
      - update
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Merge update branch into main
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin
          git checkout main
          # update ब्रांच को अपने आप main में मर्ज करेगा
          git merge origin/update -X theirs --no-edit || true
          git push origin main
